### ISSUE TITLE
Dynamic Nested Sampler Error

### ISSUE THREAD

**Issue by seVenVo1d** [ja-vazquez/SimpleMC#38]
When I enable dynamic nested sampler I am getting this error

```
Using dynamic nested sampling...
Traceback (most recent call last):
  File "/home/carman/Desktop/coding/SimpleMC/run_simplemc.py", line 7, in <module>
    analyzer.executer()
  File "/home/carman/Desktop/coding/SimpleMC/simplemc/DriverMC.py", line 159, in executer
    self.nestedRunner(iniFile=self.iniFile, **kwargs)
  File "/home/carman/Desktop/coding/SimpleMC/simplemc/DriverMC.py", line 367, in nestedRunner
    sampler.run_nested(nlive_init=nlivepoints, dlogz_init=0.05, nlive_batch=100,
TypeError: DynamicSampler.run_nested() got an unexpected keyword argument 'simpleLike'
Traceback (most recent call last):
  File "/home/carman/Desktop/coding/SimpleMC/run_simplemc.py", line 7, in <module>
    analyzer.executer()
  File "/home/carman/Desktop/coding/SimpleMC/simplemc/DriverMC.py", line 159, in executer
    self.nestedRunner(iniFile=self.iniFile, **kwargs)
  File "/home/carman/Desktop/coding/SimpleMC/simplemc/DriverMC.py", line 367, in nestedRunner
    sampler.run_nested(nlive_init=nlivepoints, dlogz_init=0.05, nlive_batch=100,
TypeError: DynamicSampler.run_nested() got an unexpected keyword argument 'simpleLike'
```

Is it not usable or there's some sort of bug ?

**Comment by seVenVo1d** [comment]
I was actually making a test run. I was trying LCDM with Planck_15 dataset.

Here are my base parameters

```
# Base parameters.
Om_par = Parameter("Om", 0.300, 0.03, (0.05, 1), "\Omega_m")
Obh2_par = Parameter("Obh2", 0.02234, 0.001, (0.02, 0.025), "\Omega_{b}h^2")
h_par = Parameter("h", 0.675, 0.03, (0.4, 1.0), "h")
```
And my `.ini' file: [baseConfig.txt](https://github.com/ja-vazquez/SimpleMC/files/9815156/baseConfig.txt)

>Note: GithHub does not allow `.ini` files to upload. So I changed it to `.txt` just to send the file.
